# -*- coding: utf-8 -*-
"""Retos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcewq62fG58MFOzms5a2qya_LjFKnomi
"""

#reto1
#entradas

salario_base, horas_extra, bonificacion = input().split()
salario_base= float(salario_base)
horas_extra= int(horas_extra)
bonificacion= int(bonificacion)

#valores

valor_hora= salario_base/192
valor_extra= (valor_hora*1.25)*horas_extra
valor_bonif= (salario_base*0.05)*bonificacion
#salario_total
salario_total= salario_base+valor_extra+valor_bonif

#descuentos

desc_salud= salario_total *0.035
desc_pension= salario_total *0.04
desc_caja= salario_total *0.01

#salario_final

salario_final= salario_total-desc_salud-desc_pension-desc_caja

print(round(salario_final,1))

#RETO 2

#entradas

distancia, velocidad_maxima_permitida, tiempo = [int(valor) for valor in input().split()]
 

distancia/= 1000
tiempo/= 3600

velocidad_media= distancia/tiempo
velocidad_media_mas_porcentaje= velocidad_maxima_permitida*1.20

if velocidad_media < velocidad_maxima_permitida:
  print("OK")
elif velocidad_media > velocidad_maxima_permitida and velocidad_media < velocidad_media_mas_porcentaje:
  print("MULTA")
elif tiempo < 0 or velocidad_maxima_permitida < 0:
  print("ERROR")
elif velocidad_maxima_permitida < velocidad_media and velocidad_media >= velocidad_media_mas_porcentaje:
  print("CURSO SENSIBILIZACION")