# -*- coding: utf-8 -*-
"""Reto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcewq62fG58MFOzms5a2qya_LjFKnomi
"""

#entradas
salariobase, horasextra, bonificacion= input().split()

salariobase= float(salariobase)
horasextra= float(horasextra)
bonificacion= float(bonificacion)

#proceso

valorhoranormal= float(salariobase/192)
valorhoraextra= int(valorhoranormal*0.25)+ valorhoranormal
bonificacion= 0

if horasextra > 3:
  bonificacion= salariobase*0.05

salariototal= salariobase+(valorhoraextra*horasextra)+bonificacion

#descuentos

salud= salariobase*0.035
pension= salariobase*0.04
cajacompensacion= salariobase*0.01

descuentos= salud+pension+cajacompensacion

salariofinal= salariototal-descuentos

print(round(salariofinal,1))

#entradas

salario_base, horas_extra, bonificacion = input().split()
salario_base= float(salario_base)
horas_extra= int(horas_extra)
bonificacion= int(bonificacion)

#valores

valor_hora= salario_base/192
valor_extra= (valor_hora*1.25)*horas_extra
valor_bonif= (salario_base*0.05)*bonificacion
#salario_total
salario_total= salario_base+valor_extra+valor_bonif

#descuentos

desc_salud= salario_total *0.035
desc_pension= salario_total *0.04
desc_caja= salario_total *0.01

#salario_final

salario_final= salario_total-desc_salud-desc_pension-desc_caja

print(round(salario_final,1))